Fix DB check always failing
Fix DB check always failing, attempt 2

Fix DB check always failing, attempt 3

diff --git a/.github/workflows/db-check.yml b/.github/workflows/db-check.yml
--- a/.github/workflows/db-check.yml
+++ b/.github/workflows/db-check.yml
@@ -123,15 +123,17 @@ jobs:
       id: check_syntax
       shell: bash --noprofile --norc {0}
       run: |
+        exit_code=0
         checkTSV () {
           for file in $@; do
             echo "File: ${file}"
             csvlint --delimiter='\t' "${file}"
             exitstatus=$?
 
-            [[ ${exitstatus} == 1 ]] \
-            && echo "::set-output name=failed::true" \
-            && failed=true
+            if [[ ${exitstatus} == 1 ]]; then
+              echo "::set-output name=failed::true"
+              exit_code=1
+            fi
           done
         }
 
@@ -149,7 +151,7 @@ jobs:
         echo "::remove-matcher owner=csvlint_error::"
         echo "::remove-matcher owner=csvlint_warning::"
         
-        [[ ${failed} == "true" ]] && exit 1
+        exit ${exit_code}
 
     - name: Get file changes
       id: changes
