Add more debug msgs

diff --git a/.github/workflows/db-check.yml b/.github/workflows/db-check.yml
--- a/.github/workflows/db-check.yml
+++ b/.github/workflows/db-check.yml
@@ -135,14 +135,17 @@ jobs:
           if [[ -d ${path} ]]; then
             for file in $(find ${path} -type f -iname "*.tsv"); do
               checkTSV "${file}"
-              last_exit_code=$?
+              last_exit_code=$? && \
+              echo "::debug::OK: ${last_exit_code}"
             done
           elif [[ -f ${path} ]]; then
             checkTSV "${path}"
-            last_exit_code=$?
+            last_exit_code=$? && \
+            echo "::debug::OK: ${last_exit_code}"
           fi
           
-          (( $last_exit_code > $exit_code )) && exit_code=${last_exit_code}
+          (( $last_exit_code > $exit_code )) && exit_code=${last_exit_code} \
+          && echo "::debug::Check failed, setting exit_code to ${exit_code}"
         done
         echo "::remove-matcher owner=csvlint_error::"
         echo "::remove-matcher owner=csvlint_warning::"
