Revert "Update Lua linter"
This partially reverts commit 6fa24145fcd9a27f35043a79bf93449a61693f9c.

diff --git a/.github/workflows/lua-lint.yml b/.github/workflows/lua-lint.yml
--- a/.github/workflows/lua-lint.yml
+++ b/.github/workflows/lua-lint.yml
@@ -27,8 +27,8 @@ on:
   workflow_dispatch:
 
 env:
-  # Include these files as regular expression
-  FILES_TO_CHECK: script/.*
+  FILES_TO_CHECK: >-
+    script/
   GIT_AUTHOR_NAME: "github-actions[bot]"
   GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
   GIT_COMMITTER_NAME: "github-actions[bot]"
@@ -38,7 +38,8 @@ env:
   UPDATE_LUA_GLOBALS_SCRIPT: .github/update_lua_globals.sh
   LUACHECK_CONFIG: >-
     .luacheckrc
-    .github/linters/.luacheckrc
+  LUA_VERSION: "5.1"
+  LUAROCKS_VERSION: "3.7.0"
   CUSTOM_LUA_GLOBALS: >-
     ae
     ardm
@@ -55,6 +56,17 @@ jobs:
       with:
         persist-credentials: false
         fetch-depth: 0
+
+    - uses: leafo/gh-actions-lua@v8.0.0
+      with:
+        luaVersion: ${{ env.LUA_VERSION }}
+        
+    - uses: leafo/gh-actions-luarocks@v4.1.0
+      with:
+        luarocksVersion: ${{ env.LUAROCKS_VERSION }}
+        
+    - name: Install luacheck
+      run: luarocks install luacheck
 
     - name: Reset autocomplete
       run: rm -rfv ${{ env.VENDOR_PATH }}
@@ -93,15 +105,22 @@ jobs:
           echo "::set-output name=clean::false"
         fi
 
-    - name: Lua Lint
-      uses: github/super-linter/slim@v4
-      env:
-        VALIDATE_ALL_CODEBASE: true
-        VALIDATE_LUA: true
-        DEFAULT_BRANCH: master
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        FILTER_REGEX_INCLUDE: ${{ env.FILES_TO_CHECK }}
-        USE_FIND_ALGORITHM: true
+    - name: Luacheck Lint
+      id: luacheck
+      shell: bash --noprofile --norc {0}
+      run: |
+        echo "::add-matcher::.github/luacheck-plain.json"
+        luacheck ${{ env.FILES_TO_CHECK }} \
+          --formatter plain \
+          --codes --ranges
+        exitcode=$?
+        echo "::remove-matcher owner=luacheck-plain_error::"
+        echo "::remove-matcher owner=luacheck-plain_warning::"
+        if [ "$exitcode" -gt 1 ]; then
+          exit $exitcode;
+        else
+          exit 0;
+        fi
 
     - name: Upload updated files
       if: steps.changes.outputs.clean == 'false'
@@ -131,7 +150,7 @@ jobs:
         path: ${{ env.VENDOR_PATH }}
 
     - name: Remove PJ-autocomplete meta files
-      run: rm -rf ${{ env.VENDOR_PATH }}/{.git,.github}
+      run: rm -rf ${{ env.VENDOR_PATH }}/{.git,.github,.vscode}
 
     - name: Download updated files
       uses: actions/download-artifact@v2
